name: BeneBlacklist

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs: 
   new-release: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Exclude unwanted files and create ZIP
        run: |
          zip -r BeneBlacklist.zip . -x '.github/*' '.gitignore' 'pkgmeta.yaml'
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Todays Build"
          files: |
            BeneBlacklist.zip
